###################
# Global Settings #
###################

stages:
  - Env
  - Build_n_Test
  - Deploy
  - Trigger

include:
  - .gitlab-ci/index.yaml

######################
# Build_n_Test Stage #
######################

.build_n_test:
  extends:
    - .job
  stage: Build_n_Test
  script:
    - module purge
    - module use ${CI_PROJECT_DIR}/spack_env
    - module load loads # module load compiler, deps, etc.
    - |
      if [[ ${CI_JOB_NAME} =~ "clang" ]];
      then
        module load clang/${FLECSISP_CLANG_VERSION};
      elif [[ ${CI_JOB_NAME} =~ "intel" ]];
      then
        module load intel/${FLECSISP_INTEL_VERSION};
      fi
    - module list
    - echo $CC
    - echo $CXX
    - mpiexec --version
    - nproc
    - echo 'Start building'
    #- ccache -z
    - mkdir -p ${CI_PROJECT_DIR}/build
    - mkdir -p ${CI_PROJECT_DIR}/build/install
    - cd ${CI_PROJECT_DIR}
    - echo "BUILDING WONTON"
    - git clone ssh://git@xcp-stash.lanl.gov:7999/laristra/wonton.git
    - cd wonton
    - git checkout ${FLECSISP_WONTON_REF}
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - |
      cmake \
        -D CMAKE_BUILD_TYPE=Release \
        -D ENABLE_UNIT_TESTS=True \
        -D WONTON_ENABLE_MPI=True \
        -D WONTON_ENABLE_THRUST=False \
        -D WONTON_ENABLE_LAPACKE=False \
        -D WONTON_ENABLE_TCMALLOC=False \
        -D CMAKE_INSTALL_PREFIX=${FLECSISP_WONTON_INSTALL_PREFIX} \
        ..
    - make -j2
    - make install
    - export CMAKE_PREFIX_PATH=${FLECSISP_WONTON_INSTALL_PREFIX}:${CMAKE_PREFIX_PATH}
    - echo "DONE BUILDING WONTON"
    - echo "BUILDING TANGRAM"
    - git clone ssh://git@xcp-stash.lanl.gov:7999/laristra/tangram.git
    - cd tangram
    - git checkout ${FLECSISP_TANGRAM_REF}
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - |
      cmake \
        -D CMAKE_BUILD_TYPE=Release \
        -D ENABLE_UNIT_TESTS=True \
        -D TANGRAM_ENABLE_MPI=True \
        -D TANGRAM_ENABLE_THRUST=False \
        -D TANGRAM_ENABLE_XMOF2D=False \
        -D XMOF2D_DIR:FILEPATH=${XMOF2D_INSTALL_PREFIX}/share/cmake \
        -D WONTON_ROOT=${FLECSISP_WONTON_INSTALL_PREFIX} \
        -D CMAKE_INSTALL_PREFIX=${FLECSISP_TANGRAM_INSTALL_PREFIX} \
        ..
    - make -j2
    - make install
    - export CMAKE_PREFIX_PATH=${FLECSISP_TANGRAM_INSTALL_PREFIX}:${CMAKE_PREFIX_PATH}
    - echo "DONE BUILDING TANGRAM"
    - echo "BUILDING PORTAGE"
    - cd ${CI_PROJECT_DIR}
    - git clone ssh://git@xcp-stash.lanl.gov:7999/laristra/portage.git
    - cd portage
    - git checkout ${FLECSISP_PORTAGE_REF}
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - |
      cmake \
        -D CMAKE_BUILD_TYPE=Release \
        -D ENABLE_UNIT_TESTS=True \
        -D ENABLE_APP_TESTS=True \
        -D PORTAGE_ENABLE_MPI=True \
        -D PORTAGE_ENABLE_THRUST=False \
        -D PORTAGE_ENABLE_TANGRAM=True \
        -D TANGRAM_ROOT=${FLECSISP_TANGRAM_INSTALL_PREFIX} \
        -D CMAKE_INSTALL_PREFIX=${FLECSISP_PORTAGE_INSTALL_PREFIX} \
        ..
    - make -j4
    - make install
    - export CMAKE_PREFIX_PATH=${FLECSISP_PORTAGE_INSTALL_PREFIX}:${CMAKE_PREFIX_PATH}
    - echo "DONE BUILDING PORTAGE"
    - cd ${CI_PROJECT_DIR}
    - git clone --recursive https://github.com/laristra/libristra.git
    - mv libristra libristra-dev
    - cd libristra-dev
    - git submodule update --init --recursive
    - mkdir -p build
    - mkdir -p build/install
    - cd build
    - |
      cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/libristra-dev/build/install \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_LUA=ON \
            -DENABLE_UNIT_TESTS=ON \
            ..
    - make -k -j2 -l40 || make VERBOSE=1
    - make install
    - export CMAKE_PREFIX_PATH=${CI_PROJECT_DIR}/libristra-dev/build/install:$CMAKE_PREFIX_PATH
    - cd ${CI_PROJECT_DIR}
    - git clone --recursive https://github.com/laristra/flecsi.git
    - mv flecsi flecsi-dev
    - cd flecsi-dev
    - git checkout l1-milestone
    - git submodule update --init --recursive
    - mkdir -p build
    - mkdir -p build/install
    - cd build
    - |
      cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/flecsi-dev/build/install \
            -DCMAKE_BUILD_TYPE=Release \
            -DFLECSI_RUNTIME_MODEL=$FLECSISP_RUNTIME \
            -DENABLE_FLECSIT=OFF \
            -DENABLE_FLECSI_TUTORIAL=OFF \
            -DENABLE_UNIT_TESTS=ON \
            -DENABLE_DOXYGEN=OFF \
            -DENABLE_DOCUMENTATION=OFF \
            -DENABLE_COVERAGE_BUILD=OFF \
            ..
    - make -k VERBOSE=1 -j2 -l40
    - make install
    - export CMAKE_PREFIX_PATH=${CI_PROJECT_DIR}/flecsi-dev/build/install:$CMAKE_PREFIX_PATH
    - echo ${CMAKE_PREFIX_PATH}
    - cd ${CI_PROJECT_DIR}/build/
    - |
      cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/build/install \
            -DCMAKE_BUILD_TYPE=$FLECSISP_BUILD_TYPE \
            -DFLECSI_RUNTIME_MODEL=$FLECSISP_RUNTIME \
            -DENABLE_UNIT_TESTS=ON \
            ..
    - make -k -j2 -l40 || make VERBOSE=1
    - make install DESTDIR=${CI_PROJECT_DIR}/build/install
    #- make install
    #- ccache -s
    - echo 'Start testing'
    - cd ${CI_PROJECT_DIR}/build/
    - make CTEST_OUTPUT_ON_FAILURE=1 test
    #- gcovr .

#######################################################################################
#######################################################################################
#######################################################################################
